### ISSUE TITLE
SHA based diff for trunk based deployment

### ISSUE THREAD

**Issue by runerys** [petabridge/Incrementalist#416]
Brilliant tool!

I've been digging a bit into it and it looks promising. We do trunk-based development and want to build and deploy affected microservices.

We use GitHub Actions and my plan was to use the "affected projects" file and build docker images based on that.

BUT: The feature branch is already merged (and deleted) at this time, so `git diff` against trunk itself doesn't work (in a nice way).

However, if I could just send the SHA before push as a parameter to `incrementalist`, instead of using the provided branch-diff-features, I think it would work. GitHub Actions provide this SHA in events.

Could this be a useful feature for your tool, or is it already possible, or am I doing it all wrong? :)

Best regards,
Rune Rystad

**Comment by Aaronontheweb** [comment]
@runerys can you show me an example of what a CLI command expressing this intention would look like?

**Comment by Aaronontheweb** [comment]
I think I'm getting the gist of what you're asking, but that would solidify it for me

**Comment by Aaronontheweb** [comment]
`incrementalist run --start-sha x --end--sha y -- build -c Release` ?

**Comment by runerys** [comment]
I fiddled around with a fork a bit, and it seems that I only need one SHA. And it can actually replace the branch parameter.

When doing a run, I either want to compare against a branch (current feature), OR I want to compare my state against a specific SHA.

`incrementalist --dry --compare-sha x`

To really understand what I was looking for, I created a spike and a draft PR here: https://github.com/petabridge/Incrementalist/pull/418

**Comment by runerys** [comment]
I will test one more thing. If I have a commit sha, perhaps I can just check this out to a local branch and run the tool against that...

**Comment by Aaronontheweb** [comment]
Good - I was thinking that using a SHA for the `-b` / `--branch` parameter would work fine for the base case.

**Comment by runerys** [comment]
The new idea works. I don't need an explicit feature in the tool to compare against a commit sha after all.

Here are some steps from my build process. The commit in `github.event.before` is only available for push-events.

```yaml
...
steps:
- name: Checkout code
  uses: actions/checkout@v4
  with:
    fetch-depth: 0 # <- Required to get commit history + trunk branch on PR builds

- name: Restore dotnet tools from manifest
  run: dotnet tool restore

- name: Run incrementalist on push against previous commit
  if: github.event_name == 'push'
  run: |
    git branch previous_commit ${{ github.event.before }} # <-- Create temporary branch
    dotnet incrementalist run --dry -b previous_commit -f ./affected_projects.txt

- name: Run incrementalist on PR against trunk
  if: github.event_name == 'pull_request'
  run: |
    dotnet incrementalist run --dry -b trunk -f ./affected_projects.txt
# Other GitHub Events: No affected_projects.txt file => Build all apps

...
# Further: Some fancy jq stuff to filter my applications against affected projects and create input for a matrix build.
```

I will close the draft PR, and you can close this issue :)

Best regards,
Rune
